### ISSUE TITLE
 Is it supported on Ubuntu? and i got some trouble ;ida can not install idacode plugin 

### ISSUE THREAD

**Issue by xjy-xing** [ioncodes/idacode#30]
Warning
**idacode.py. invalid Python installation: unable to open** /home/alay/Desktop/ida/lilb/python2.7/**coniglMakefle (No such file o drectory)Traceback (most recent call last):**

![image](https://user-images.githubusercontent.com/68682239/141967377-39a729a9-b68a-4c61-82d9-f3010a42e21a.png)

File "/home/alay/Desktop/ida_dt/ida_in/python/idaapi.py", line 558, in lDAPython_ExecScript execfile(script, g)

File "/home/alay/Desktop/ida_dt/ida_in/plugins/idacode.py", line 3, in <module>
import idacode_utils.plugin as plugin
File "/home/alay/Desktop/ida_dt/ida_in/plugins/idacode_utils/plugin.py" , line 8, in <module>
import idacode_utils.dbg as dbg
File "/home/alay/Desktop/ida_dt/ida_in/plugins/idacode_utils/dbg.py", line 2, in <module>
from debugpy.server import api
File "/home/alay/Desktop/ida_dt/ida_in/python/lib/python2.7/debugpy/server/_init_.py", line 9, in <module>import debugpy._vendored.force_pydevd # noqa
File "/home/alay/Desktop/lida_dtlida_in/python/ib/python2.7/debugpyl_vendored/force pydevd.py", line 54, in <module>'pydevd',
File "/home/alay/Desktop/ida_dt/ida_in/python/lib/

**Comment by xjy-xing** [comment]
I reconfigured the environment in Windows and everything worked without error, thank you very much

**Comment by ioncodes** [comment]
Glad it works!

**Comment by ioncodes** [comment]
Let me know if you have future questions about Ubuntu. It should work, however, your screenshot suggests that there's something wrong with your Python/IDA installation as it's trying to load a Makefile.
